---
# tasks file for mailx

- name: Install required packages
  become: True
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - bsd-mailx
    - sendmail

- name: Configure mailx for the user
  become: True
  template:
    src: mailrc.j2
    dest: ~/.mailrc
    mode: 0600

- name: Create mail link
  become: True
  file:
    dest: /usr/bin/mail
    src: /usr/bin/bsd-mailx
    state: link
